### ISSUE TITLE
ctypes.ArgumentError with file_reader on Python 3

### ISSUE THREAD

**Issue by bfontaine** [dsoprea/PyEasyArchive#12]
With Python 3.4:

``` pycon
>>> with libarchive.public.file_reader("myfile.7z") as reader:
...     pass
... 
Traceback (most recent call last):
  File "…/venv/lib/python3.4/site-packages/libarchive/adapters/archive_read.py", line 63, in _archive_read_open_filename
    block_size_bytes)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "…/venv/lib/python3.4/site-packages/libarchive/adapters/archive_read.py", line 275, in _enumerator
    opener(archive_res)
  File "…/venv/lib/python3.4/site-packages/libarchive/adapters/archive_read.py", line 298, in opener
    _archive_read_open_filename(archive_res, filepath, block_size)
  File "…/venv/lib/python3.4/site-packages/libarchive/adapters/archive_read.py", line 66, in _archive_read_open_filename
    raise libarchive.exception.ArchiveError(message)
libarchive.exception.ArchiveError: None
```

It works fine with Python 2.7:

``` pycon
>>> with libarchive.public.file_reader("myfile.7z") as reader:
...     pass
... 
>>>
```

It seems to work if I force Python 3 to use bytes:

``` pycon
>>> with libarchive.public.file_reader(bytes("myfile.7z", "ascii")) as reader:
...     pass
...
```

**Comment by HeWenxuan1994** [comment]
In Python 2.7, strings are byte-strings by default. In Python 3.x, they are unicode by default. Try explicitly making your string a byte string using .encode('ascii') before handing it to DLL.prepare.
So,you can transfor the file name as below:
>>>filename = str("myfile.7z").encode('ascii')
