### ISSUE TITLE
password encrypted zip files raise exception

### ISSUE THREAD

**Issue by SkyLeach** [dsoprea/PyEasyArchive#20]
afaict libarchive does support this, does pyeasyarchive provide a hook?

```
 '_asdict',
 '_fields',
 '_make',
 '_replace',
 'count',
 'index']
Traceback (most recent call last):
  File "/Users/magregor/tmp/test_lafh.py", line 22, in <module>
    for block in entry.get_blocks():
  File "/Users/magregor/.virtualenvs/imgunbundler/lib/python2.7/site-packages/libarchive/adapters/archive_read.py", line 219, in get_blocks
    for block in _read_by_block(self.reader_res):
  File "/Users/magregor/.virtualenvs/imgunbundler/lib/python2.7/site-packages/libarchive/adapters/archive_read.py", line 210, in _read_by_block
    (r,))
ValueError: Read failed (archive_read_data_block): (-30)```

**Comment by dsoprea** [comment]
Nope.
